// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (feed_id, created_at, updated_at, feed_name, feed_url, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING feed_id, created_at, updated_at, feed_name, feed_url, user_id
`

type CreateFeedParams struct {
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FeedName  string
	FeedUrl   string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FeedName,
		arg.FeedUrl,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedName,
		&i.FeedUrl,
		&i.UserID,
	)
	return i, err
}
